insert into public.content_items(item_id, content_kind, ranked_activities, difficulty, answer_key, ranked_enabled)
values
('u1-fc-1', 'flashcard', array['match', 'memory']::text[], 1, '{"term":"Denary","definition":"A base 10 number system using the digits 0-9."}'::jsonb, true),
('u1-fc-2', 'flashcard', array['match', 'memory']::text[], 1, '{"term":"Binary","definition":"A base 2 number system using only the digits 0 and 1."}'::jsonb, true),
('u1-fc-3', 'flashcard', array['match', 'memory']::text[], 1, '{"term":"Hexadecimal","definition":"A base 16 number system using 0-9 and A-F."}'::jsonb, true),
('u1-fc-4', 'flashcard', array['match', 'memory']::text[], 1, '{"term":"Why computers use binary","definition":"The CPU is built from logic gates with two states (on/off), so all data must be converted to binary to be processed and stored in registers."}'::jsonb, true),
('u1-fc-5', 'flashcard', array['match', 'memory']::text[], 1, '{"term":"Why hexadecimal is used","definition":"It is a shorter, easier representation of binary for humans to read and write, e.g. MAC addresses, colour codes, memory addresses and error codes."}'::jsonb, true),
('u1-fc-6', 'flashcard', array['match', 'memory']::text[], 2, '{"term":"Overflow","definition":"An error that occurs when a calculation produces a value larger than the number of bits can hold (e.g. greater than 255 in an 8-bit register)."}'::jsonb, true),
('u1-fc-7', 'flashcard', array['match', 'memory']::text[], 2, '{"term":"Logical left shift","definition":"Moves all bits left; zeros fill in from the right; bits lost off the left end. Each shift of one place multiplies the value by 2."}'::jsonb, true),
('u1-fc-8', 'flashcard', array['match', 'memory']::text[], 2, '{"term":"Logical right shift","definition":"Moves all bits right; zeros fill in from the left; bits lost off the right end. Each shift of one place divides the value by 2."}'::jsonb, true),
('u1-fc-9', 'flashcard', array['match', 'memory']::text[], 3, '{"term":"Two''s complement","definition":"A method of representing positive and negative 8-bit binary integers, where the most significant bit has a negative place value."}'::jsonb, true),
('u1-fc-10', 'flashcard', array['match', 'memory']::text[], 1, '{"term":"Most significant bit (MSB)","definition":"The left-most bit in a binary number, which has the largest place value."}'::jsonb, true),
('u1-fc-11', 'flashcard', array['match', 'memory']::text[], 1, '{"term":"Character set","definition":"All of the characters and symbols that can be represented by a computer system."}'::jsonb, true),
('u1-fc-12', 'flashcard', array['match', 'memory']::text[], 1, '{"term":"ASCII","definition":"American Standard Code for Information Interchange; a character set that uses 7 bits to represent 128 characters."}'::jsonb, true),
('u1-fc-13', 'flashcard', array['match', 'memory']::text[], 1, '{"term":"Unicode","definition":"A character set that represents many more characters than ASCII (many languages and emojis), but requires more bits per character."}'::jsonb, true),
('u1-fc-14', 'flashcard', array['match', 'memory']::text[], 1, '{"term":"Sample rate","definition":"The number of sound samples taken per second (measured in hertz)."}'::jsonb, true),
('u1-fc-15', 'flashcard', array['match', 'memory']::text[], 1, '{"term":"Sample resolution","definition":"The number of bits used to store each sound sample."}'::jsonb, true),
('u1-fc-16', 'flashcard', array['match', 'memory']::text[], 1, '{"term":"Pixel","definition":"The smallest element (a single dot) of a digital image."}'::jsonb, true),
('u1-fc-17', 'flashcard', array['match', 'memory']::text[], 1, '{"term":"Resolution (image)","definition":"The number of pixels in an image (width x height)."}'::jsonb, true),
('u1-fc-18', 'flashcard', array['match', 'memory']::text[], 1, '{"term":"Colour depth","definition":"The number of bits used to represent the colour of each pixel."}'::jsonb, true),
('u1-fc-19', 'flashcard', array['match', 'memory']::text[], 1, '{"term":"Effect of higher sample rate/resolution","definition":"A more accurate sound recording, but a larger file size."}'::jsonb, true),
('u1-fc-20', 'flashcard', array['match', 'memory']::text[], 1, '{"term":"Bit","definition":"A single binary digit, 0 or 1."}'::jsonb, true),
('u1-fc-21', 'flashcard', array['match', 'memory']::text[], 1, '{"term":"Nibble","definition":"A group of 4 bits."}'::jsonb, true),
('u1-fc-22', 'flashcard', array['match', 'memory']::text[], 1, '{"term":"Byte","definition":"A group of 8 bits."}'::jsonb, true),
('u1-fc-23', 'flashcard', array['match', 'memory']::text[], 1, '{"term":"Kibibyte (KiB)","definition":"1024 bytes (calculations use 1024, not 1000)."}'::jsonb, true),
('u1-fc-24', 'flashcard', array['match', 'memory']::text[], 1, '{"term":"Mebibyte (MiB)","definition":"1024 kibibytes."}'::jsonb, true),
('u1-fc-25', 'flashcard', array['match', 'memory']::text[], 1, '{"term":"Data compression","definition":"Reducing the size of a file so it needs less storage and bandwidth and transmits faster."}'::jsonb, true),
('u1-fc-26', 'flashcard', array['match', 'memory']::text[], 2, '{"term":"Lossy compression","definition":"Reduces file size by permanently removing data, e.g. reducing image resolution/colour depth or sound sample rate/resolution. Quality is reduced."}'::jsonb, true),
('u1-fc-27', 'flashcard', array['match', 'memory']::text[], 2, '{"term":"Lossless compression","definition":"Reduces file size without any permanent loss of data, so the original file can be fully restored, e.g. run length encoding (RLE)."}'::jsonb, true),
('u1-fc-28', 'flashcard', array['match', 'memory']::text[], 2, '{"term":"Run length encoding (RLE)","definition":"A lossless compression method that stores a repeated run of values as a single value plus a count."}'::jsonb, true),
('u1-mcq-1', 'mcq', array['quiz']::text[], 2, '{"answerIndex":1}'::jsonb, true),
('u1-mcq-2', 'mcq', array['quiz']::text[], 2, '{"answerIndex":0}'::jsonb, true),
('u1-mcq-3', 'mcq', array['quiz']::text[], 1, '{"answerIndex":2}'::jsonb, true),
('u1-mcq-4', 'mcq', array['quiz']::text[], 1, '{"answerIndex":0}'::jsonb, true),
('u1-mcq-5', 'mcq', array['quiz']::text[], 1, '{"answerIndex":1}'::jsonb, true),
('u1-mcq-6', 'mcq', array['quiz']::text[], 1, '{"answerIndex":1}'::jsonb, true),
('u1-mcq-7', 'mcq', array['quiz']::text[], 2, '{"answerIndex":1}'::jsonb, true),
('u1-mcq-8', 'mcq', array['quiz']::text[], 2, '{"answerIndex":3}'::jsonb, true),
('u1-mcq-9', 'mcq', array['quiz']::text[], 1, '{"answerIndex":2}'::jsonb, true),
('u1-mcq-10', 'mcq', array['quiz']::text[], 1, '{"answerIndex":1}'::jsonb, true),
('u1-mcq-11', 'mcq', array['quiz']::text[], 1, '{"answerIndex":1}'::jsonb, true),
('u1-mcq-12', 'mcq', array['quiz']::text[], 1, '{"answerIndex":1}'::jsonb, true),
('u1-mcq-13', 'mcq', array['quiz']::text[], 1, '{"answerIndex":1}'::jsonb, true),
('u1-mcq-14', 'mcq', array['quiz']::text[], 1, '{"answerIndex":1}'::jsonb, true),
('u1-mcq-15', 'mcq', array['quiz']::text[], 1, '{"answerIndex":1}'::jsonb, true),
('u1-mcq-16', 'mcq', array['quiz']::text[], 2, '{"answerIndex":1}'::jsonb, true),
('u1-mcq-17', 'mcq', array['quiz']::text[], 1, '{"answerIndex":1}'::jsonb, true),
('u1-mcq-18', 'mcq', array['quiz']::text[], 1, '{"answerIndex":2}'::jsonb, true),
('u1-mcq-19', 'mcq', array['quiz']::text[], 2, '{"answerIndex":1}'::jsonb, true),
('u2-fc-1', 'flashcard', array['match', 'memory']::text[], 1, '{"term":"Packet","definition":"A small unit that data is broken down into so it can be transmitted across a network."}'::jsonb, true),
('u2-fc-2', 'flashcard', array['match', 'memory']::text[], 1, '{"term":"Packet header","definition":"The part of a packet containing the destination address, packet number and originator''s (sender''s) address."}'::jsonb, true),
('u2-fc-3', 'flashcard', array['match', 'memory']::text[], 1, '{"term":"Payload","definition":"The actual data being carried inside a packet."}'::jsonb, true),
('u2-fc-4', 'flashcard', array['match', 'memory']::text[], 1, '{"term":"Trailer","definition":"The part of a packet that marks the end of the packet and can contain error-checking data."}'::jsonb, true),
('u2-fc-5', 'flashcard', array['match', 'memory']::text[], 2, '{"term":"Packet switching","definition":"Data is split into packets, each can take a different route controlled by routers, and packets are reordered at the destination once the last one arrives."}'::jsonb, true),
('u2-fc-6', 'flashcard', array['match', 'memory']::text[], 1, '{"term":"Serial transmission","definition":"Bits are sent one after another down a single wire/channel."}'::jsonb, true),
('u2-fc-7', 'flashcard', array['match', 'memory']::text[], 1, '{"term":"Parallel transmission","definition":"Several bits are sent at the same time down multiple wires/channels."}'::jsonb, true),
('u2-fc-8', 'flashcard', array['match', 'memory']::text[], 1, '{"term":"Simplex","definition":"Data is transmitted in one direction only."}'::jsonb, true),
('u2-fc-9', 'flashcard', array['match', 'memory']::text[], 1, '{"term":"Half-duplex","definition":"Data is transmitted in both directions, but only one direction at a time."}'::jsonb, true),
('u2-fc-10', 'flashcard', array['match', 'memory']::text[], 1, '{"term":"Full-duplex","definition":"Data is transmitted in both directions at the same time."}'::jsonb, true),
('u2-fc-11', 'flashcard', array['match', 'memory']::text[], 1, '{"term":"USB","definition":"Universal Serial Bus; a common serial interface used to connect devices and transmit data."}'::jsonb, true),
('u2-fc-12', 'flashcard', array['match', 'memory']::text[], 1, '{"term":"Why errors occur","definition":"Interference during transmission can cause data loss, data gain or data change."}'::jsonb, true),
('u2-fc-13', 'flashcard', array['match', 'memory']::text[], 2, '{"term":"Parity check","definition":"An extra parity bit is added so the number of 1s is odd or even; if the parity does not match on arrival, an error is detected."}'::jsonb, true),
('u2-fc-14', 'flashcard', array['match', 'memory']::text[], 3, '{"term":"Parity block check","definition":"Parity bits are calculated across both rows and columns of a block of data so the exact position of an error can be found."}'::jsonb, true),
('u2-fc-15', 'flashcard', array['match', 'memory']::text[], 2, '{"term":"Checksum","definition":"A value calculated from the data is sent with it; the receiver recalculates and compares to check for errors."}'::jsonb, true),
('u2-fc-16', 'flashcard', array['match', 'memory']::text[], 1, '{"term":"Echo check","definition":"The received data is sent back to the sender and compared with the original to check for errors."}'::jsonb, true),
('u2-fc-17', 'flashcard', array['match', 'memory']::text[], 2, '{"term":"Check digit","definition":"An extra digit calculated from the others and added to data to detect data-entry errors, e.g. in ISBNs and barcodes."}'::jsonb, true),
('u2-fc-18', 'flashcard', array['match', 'memory']::text[], 2, '{"term":"Automatic Repeat reQuest (ARQ)","definition":"Uses positive/negative acknowledgements and a timeout to confirm data is received without error and request retransmission if not."}'::jsonb, true),
('u2-fc-19', 'flashcard', array['match', 'memory']::text[], 1, '{"term":"Encryption","definition":"Scrambling data so that it is meaningless if it is intercepted during transmission."}'::jsonb, true),
('u2-fc-20', 'flashcard', array['match', 'memory']::text[], 1, '{"term":"Plaintext","definition":"The original, readable data before it is encrypted."}'::jsonb, true),
('u2-fc-21', 'flashcard', array['match', 'memory']::text[], 1, '{"term":"Ciphertext","definition":"The scrambled, encrypted data."}'::jsonb, true),
('u2-fc-22', 'flashcard', array['match', 'memory']::text[], 1, '{"term":"Symmetric encryption","definition":"The same key is used to both encrypt and decrypt the data."}'::jsonb, true),
('u2-fc-23', 'flashcard', array['match', 'memory']::text[], 2, '{"term":"Asymmetric encryption","definition":"Uses two different keys: a public key and a private key."}'::jsonb, true),
('u2-fc-24', 'flashcard', array['match', 'memory']::text[], 1, '{"term":"Encryption key","definition":"A value used by an encryption algorithm to scramble (encrypt) and unscramble (decrypt) data."}'::jsonb, true),
('u2-mcq-1', 'mcq', array['quiz']::text[], 1, '{"answerIndex":3}'::jsonb, true),
('u2-mcq-2', 'mcq', array['quiz']::text[], 1, '{"answerIndex":1}'::jsonb, true),
('u2-mcq-3', 'mcq', array['quiz']::text[], 1, '{"answerIndex":1}'::jsonb, true),
('u2-mcq-4', 'mcq', array['quiz']::text[], 1, '{"answerIndex":2}'::jsonb, true),
('u2-mcq-5', 'mcq', array['quiz']::text[], 1, '{"answerIndex":1}'::jsonb, true),
('u2-mcq-6', 'mcq', array['quiz']::text[], 2, '{"answerIndex":1}'::jsonb, true),
('u2-mcq-7', 'mcq', array['quiz']::text[], 1, '{"answerIndex":2}'::jsonb, true),
('u2-mcq-8', 'mcq', array['quiz']::text[], 1, '{"answerIndex":1}'::jsonb, true),
('u2-mcq-9', 'mcq', array['quiz']::text[], 2, '{"answerIndex":1}'::jsonb, true),
('u2-mcq-10', 'mcq', array['quiz']::text[], 1, '{"answerIndex":1}'::jsonb, true),
('u2-mcq-11', 'mcq', array['quiz']::text[], 1, '{"answerIndex":1}'::jsonb, true),
('u2-mcq-12', 'mcq', array['quiz']::text[], 1, '{"answerIndex":1}'::jsonb, true),
('u2-mcq-13', 'mcq', array['quiz']::text[], 2, '{"answerIndex":1}'::jsonb, true),
('u2-mcq-14', 'mcq', array['quiz']::text[], 1, '{"answerIndex":1}'::jsonb, true),
('u2-mcq-15', 'mcq', array['quiz']::text[], 2, '{"answerIndex":1}'::jsonb, true),
('u3-fc-1', 'flashcard', array['match', 'memory']::text[], 1, '{"term":"CPU","definition":"The Central Processing Unit; processes the instructions and data that are input so a result can be output."}'::jsonb, true),
('u3-fc-2', 'flashcard', array['match', 'memory']::text[], 1, '{"term":"Microprocessor","definition":"A type of integrated circuit on a single chip."}'::jsonb, true),
('u3-fc-3', 'flashcard', array['match', 'memory']::text[], 2, '{"term":"Von Neumann architecture","definition":"An architecture where instructions and data are stored together in the same memory and processed by a single CPU."}'::jsonb, true),
('u3-fc-4', 'flashcard', array['match', 'memory']::text[], 1, '{"term":"Arithmetic Logic Unit (ALU)","definition":"The CPU component that carries out calculations and logical operations."}'::jsonb, true),
('u3-fc-5', 'flashcard', array['match', 'memory']::text[], 1, '{"term":"Control Unit (CU)","definition":"The CPU component that manages and coordinates operations and sends control signals."}'::jsonb, true),
('u3-fc-6', 'flashcard', array['match', 'memory']::text[], 2, '{"term":"Program Counter (PC)","definition":"A register that holds the address of the next instruction to be fetched."}'::jsonb, true),
('u3-fc-7', 'flashcard', array['match', 'memory']::text[], 2, '{"term":"Memory Address Register (MAR)","definition":"A register that holds the address of the data/instruction to be fetched or written."}'::jsonb, true),
('u3-fc-8', 'flashcard', array['match', 'memory']::text[], 2, '{"term":"Memory Data Register (MDR)","definition":"A register that holds the data/instruction just fetched from, or to be written to, memory."}'::jsonb, true),
('u3-fc-9', 'flashcard', array['match', 'memory']::text[], 2, '{"term":"Current Instruction Register (CIR)","definition":"A register that holds the current instruction while it is decoded and executed."}'::jsonb, true),
('u3-fc-10', 'flashcard', array['match', 'memory']::text[], 2, '{"term":"Accumulator (ACC)","definition":"A register that stores the results of calculations carried out by the ALU."}'::jsonb, true),
('u3-fc-11', 'flashcard', array['match', 'memory']::text[], 1, '{"term":"Address bus","definition":"Carries memory addresses from the CPU to memory (one direction)."}'::jsonb, true),
('u3-fc-12', 'flashcard', array['match', 'memory']::text[], 1, '{"term":"Data bus","definition":"Carries data between the CPU and memory in both directions."}'::jsonb, true),
('u3-fc-13', 'flashcard', array['match', 'memory']::text[], 1, '{"term":"Control bus","definition":"Carries control signals around the computer system."}'::jsonb, true),
('u3-fc-14', 'flashcard', array['match', 'memory']::text[], 2, '{"term":"Fetch-Decode-Execute (FDE) cycle","definition":"The cycle in which an instruction is fetched from RAM, decoded by the CU, then executed."}'::jsonb, true),
('u3-fc-15', 'flashcard', array['match', 'memory']::text[], 1, '{"term":"Core","definition":"A processing unit within a CPU; more cores allow more instructions to be processed at the same time."}'::jsonb, true),
('u3-fc-16', 'flashcard', array['match', 'memory']::text[], 1, '{"term":"Cache","definition":"Small, very fast memory inside/near the CPU that stores frequently used data and instructions to speed up processing."}'::jsonb, true),
('u3-fc-17', 'flashcard', array['match', 'memory']::text[], 1, '{"term":"Clock speed","definition":"The number of cycles the CPU performs per second (measured in hertz); a higher clock speed processes more instructions per second."}'::jsonb, true),
('u3-fc-18', 'flashcard', array['match', 'memory']::text[], 1, '{"term":"Instruction set","definition":"The list of all the commands (machine code) that a CPU can process."}'::jsonb, true),
('u3-fc-19', 'flashcard', array['match', 'memory']::text[], 2, '{"term":"Embedded system","definition":"A dedicated computer built into a larger device to perform a specific function, e.g. in a washing machine or car."}'::jsonb, true),
('u3-fc-20', 'flashcard', array['match', 'memory']::text[], 1, '{"term":"Input device","definition":"Hardware used to enter data into a computer, e.g. keyboard, optical mouse, barcode scanner, microphone."}'::jsonb, true),
('u3-fc-21', 'flashcard', array['match', 'memory']::text[], 1, '{"term":"Output device","definition":"Hardware used to output data or results, e.g. LCD/LED screen, printer, speaker, actuator."}'::jsonb, true),
('u3-fc-22', 'flashcard', array['match', 'memory']::text[], 1, '{"term":"Sensor","definition":"An input device that measures a physical quantity such as temperature, light, pressure or humidity."}'::jsonb, true),
('u3-fc-23', 'flashcard', array['match', 'memory']::text[], 1, '{"term":"Actuator","definition":"An output device that produces movement, e.g. a motor controlled by the computer."}'::jsonb, true),
('u3-fc-24', 'flashcard', array['match', 'memory']::text[], 1, '{"term":"Primary storage","definition":"Memory that is directly accessed by the CPU, including RAM and ROM."}'::jsonb, true),
('u3-fc-25', 'flashcard', array['match', 'memory']::text[], 1, '{"term":"RAM","definition":"Random Access Memory; volatile primary storage that can be read from and written to, holding currently running programs and data."}'::jsonb, true),
('u3-fc-26', 'flashcard', array['match', 'memory']::text[], 1, '{"term":"ROM","definition":"Read Only Memory; non-volatile primary storage that holds start-up/boot instructions and cannot normally be changed."}'::jsonb, true),
('u3-fc-27', 'flashcard', array['match', 'memory']::text[], 1, '{"term":"Secondary storage","definition":"Non-volatile storage that is not directly accessed by the CPU, used for more permanent storage of data."}'::jsonb, true),
('u3-fc-28', 'flashcard', array['match', 'memory']::text[], 2, '{"term":"Magnetic storage","definition":"Uses platters divided into tracks and sectors, read and written using electromagnets, e.g. a hard disk drive (HDD)."}'::jsonb, true),
('u3-fc-29', 'flashcard', array['match', 'memory']::text[], 2, '{"term":"Optical storage","definition":"Uses a laser to read and create pits and lands on a disc, e.g. CD, DVD and Blu-ray."}'::jsonb, true),
('u3-fc-30', 'flashcard', array['match', 'memory']::text[], 2, '{"term":"Solid-state storage","definition":"Uses NAND/NOR flash memory with control gates and floating gates; no moving parts, e.g. SSD, SD card, USB drive."}'::jsonb, true),
('u3-fc-31', 'flashcard', array['match', 'memory']::text[], 3, '{"term":"Virtual memory","definition":"Uses secondary storage as if it were extra RAM; pages of data are moved between RAM and virtual memory when RAM is full."}'::jsonb, true),
('u3-fc-32', 'flashcard', array['match', 'memory']::text[], 1, '{"term":"Cloud storage","definition":"Data stored on remote physical servers that is accessed over the internet, rather than stored locally."}'::jsonb, true),
('u3-fc-33', 'flashcard', array['match', 'memory']::text[], 1, '{"term":"Network Interface Card (NIC)","definition":"Hardware that a computer needs in order to connect to and access a network."}'::jsonb, true),
('u3-fc-34', 'flashcard', array['match', 'memory']::text[], 2, '{"term":"MAC address","definition":"A unique hardware address given to a NIC at manufacture (manufacturer code + serial number), usually written in hexadecimal."}'::jsonb, true),
('u3-fc-35', 'flashcard', array['match', 'memory']::text[], 2, '{"term":"IP address","definition":"An address allocated to a device on a network; it can be static or dynamic and is either IPv4 or IPv6."}'::jsonb, true),
('u3-fc-36', 'flashcard', array['match', 'memory']::text[], 1, '{"term":"Router","definition":"A device that sends data to a specific destination on a network, can assign IP addresses and can connect a local network to the internet."}'::jsonb, true),
('u3-fc-37', 'flashcard', array['match', 'memory']::text[], 1, '{"term":"Touch screen","definition":"An input device (resistive, capacitive or infra-red) that lets a user enter data by touching the display."}'::jsonb, true),
('u3-fc-38', 'flashcard', array['match', 'memory']::text[], 1, '{"term":"3D printer","definition":"An output device that builds a solid physical object by depositing material layer by layer."}'::jsonb, true),
('u3-fc-39', 'flashcard', array['match', 'memory']::text[], 2, '{"term":"Static vs dynamic IP address","definition":"A static IP address stays the same each time a device connects; a dynamic IP address can be reassigned by the network each time."}'::jsonb, true),
('u3-fc-40', 'flashcard', array['match', 'memory']::text[], 2, '{"term":"IPv4 and IPv6","definition":"Two types of IP address: IPv4 uses 32 bits (e.g. 192.168.0.1); IPv6 uses 128 bits and allows many more addresses."}'::jsonb, true),
('u3-mcq-1', 'mcq', array['quiz']::text[], 2, '{"answerIndex":2}'::jsonb, true),
('u3-mcq-2', 'mcq', array['quiz']::text[], 1, '{"answerIndex":1}'::jsonb, true),
('u3-mcq-3', 'mcq', array['quiz']::text[], 2, '{"answerIndex":1}'::jsonb, true),
('u3-mcq-4', 'mcq', array['quiz']::text[], 2, '{"answerIndex":1}'::jsonb, true),
('u3-mcq-5', 'mcq', array['quiz']::text[], 1, '{"answerIndex":2}'::jsonb, true),
('u3-mcq-6', 'mcq', array['quiz']::text[], 2, '{"answerIndex":1}'::jsonb, true),
('u3-mcq-7', 'mcq', array['quiz']::text[], 1, '{"answerIndex":1}'::jsonb, true),
('u3-mcq-8', 'mcq', array['quiz']::text[], 1, '{"answerIndex":2}'::jsonb, true),
('u3-mcq-9', 'mcq', array['quiz']::text[], 1, '{"answerIndex":0}'::jsonb, true),
('u3-mcq-10', 'mcq', array['quiz']::text[], 2, '{"answerIndex":1}'::jsonb, true),
('u3-mcq-11', 'mcq', array['quiz']::text[], 1, '{"answerIndex":1}'::jsonb, true),
('u3-mcq-12', 'mcq', array['quiz']::text[], 2, '{"answerIndex":1}'::jsonb, true),
('u3-mcq-13', 'mcq', array['quiz']::text[], 2, '{"answerIndex":2}'::jsonb, true),
('u3-mcq-14', 'mcq', array['quiz']::text[], 3, '{"answerIndex":1}'::jsonb, true),
('u3-mcq-15', 'mcq', array['quiz']::text[], 1, '{"answerIndex":1}'::jsonb, true),
('u3-mcq-16', 'mcq', array['quiz']::text[], 2, '{"answerIndex":1}'::jsonb, true),
('u3-mcq-17', 'mcq', array['quiz']::text[], 2, '{"answerIndex":1}'::jsonb, true),
('u3-mcq-18', 'mcq', array['quiz']::text[], 1, '{"answerIndex":1}'::jsonb, true),
('u3-mcq-19', 'mcq', array['quiz']::text[], 1, '{"answerIndex":1}'::jsonb, true),
('u3-mcq-20', 'mcq', array['quiz']::text[], 1, '{"answerIndex":2}'::jsonb, true),
('u3-mcq-21', 'mcq', array['quiz']::text[], 2, '{"answerIndex":1}'::jsonb, true),
('u3-mcq-22', 'mcq', array['quiz']::text[], 1, '{"answerIndex":1}'::jsonb, true),
('u3-mcq-23', 'mcq', array['quiz']::text[], 2, '{"answerIndex":2}'::jsonb, true),
('u3-mcq-24', 'mcq', array['quiz']::text[], 2, '{"answerIndex":1}'::jsonb, true),
('u7-fc-1', 'flashcard', array['match', 'memory']::text[], 1, '{"term":"Program Development Life Cycle (PDLC)","definition":"The stages of developing a program: analysis, design, coding and testing."}'::jsonb, true),
('u7-fc-2', 'flashcard', array['match', 'memory']::text[], 1, '{"term":"Analysis","definition":"Identifying the problem and requirements, using abstraction and decomposition."}'::jsonb, true),
('u7-fc-3', 'flashcard', array['match', 'memory']::text[], 1, '{"term":"Design","definition":"Planning the solution using decomposition, structure diagrams, flowcharts and pseudocode."}'::jsonb, true),
('u7-fc-4', 'flashcard', array['match', 'memory']::text[], 1, '{"term":"Coding","definition":"Writing the program code and carrying out iterative testing."}'::jsonb, true),
('u7-fc-5', 'flashcard', array['match', 'memory']::text[], 1, '{"term":"Testing","definition":"Checking that the program works correctly and produces the expected results."}'::jsonb, true),
('u7-fc-6', 'flashcard', array['match', 'memory']::text[], 2, '{"term":"Abstraction","definition":"Removing or hiding unnecessary detail so only the important parts of a problem remain."}'::jsonb, true),
('u7-fc-7', 'flashcard', array['match', 'memory']::text[], 2, '{"term":"Decomposition","definition":"Breaking a problem down into its component parts: inputs, processes, outputs and storage."}'::jsonb, true),
('u7-fc-8', 'flashcard', array['match', 'memory']::text[], 1, '{"term":"Structure diagram","definition":"A hierarchical (top-down) diagram showing how a system is broken into sub-systems."}'::jsonb, true),
('u7-fc-9', 'flashcard', array['match', 'memory']::text[], 1, '{"term":"Flowchart","definition":"A diagram that uses standard symbols to show the steps and flow of an algorithm."}'::jsonb, true),
('u7-fc-10', 'flashcard', array['match', 'memory']::text[], 1, '{"term":"Pseudocode","definition":"A way of describing an algorithm using structured, English-like statements (not a real programming language)."}'::jsonb, true),
('u7-fc-11', 'flashcard', array['match', 'memory']::text[], 1, '{"term":"Sequence","definition":"Statements that are carried out one after another, in order."}'::jsonb, true),
('u7-fc-12', 'flashcard', array['match', 'memory']::text[], 1, '{"term":"Selection","definition":"Choosing between different paths using a condition, e.g. IF or CASE statements."}'::jsonb, true),
('u7-fc-13', 'flashcard', array['match', 'memory']::text[], 1, '{"term":"Iteration","definition":"Repeating statements using a loop, e.g. FOR (count-controlled) or WHILE (condition-controlled)."}'::jsonb, true),
('u7-fc-14', 'flashcard', array['match', 'memory']::text[], 1, '{"term":"Decision symbol","definition":"The diamond/rhombus flowchart symbol used for a question with a Yes/No (true/false) answer."}'::jsonb, true),
('u7-fc-15', 'flashcard', array['match', 'memory']::text[], 1, '{"term":"Pseudocode assignment","definition":"Uses the left arrow, e.g. Count ← 0 stores the value 0 in the variable Count."}'::jsonb, true),
('u7-mcq-1', 'mcq', array['quiz']::text[], 1, '{"answerIndex":1}'::jsonb, true),
('u7-mcq-2', 'mcq', array['quiz']::text[], 2, '{"answerIndex":1}'::jsonb, true),
('u7-mcq-3', 'mcq', array['quiz']::text[], 2, '{"answerIndex":1}'::jsonb, true),
('u7-mcq-4', 'mcq', array['quiz']::text[], 1, '{"answerIndex":1}'::jsonb, true),
('u7-mcq-5', 'mcq', array['quiz']::text[], 1, '{"answerIndex":1}'::jsonb, true),
('u7-mcq-6', 'mcq', array['quiz']::text[], 1, '{"answerIndex":1}'::jsonb, true),
('u7-mcq-7', 'mcq', array['quiz']::text[], 2, '{"answerIndex":1}'::jsonb, true),
('u7-mcq-8', 'mcq', array['quiz']::text[], 1, '{"answerIndex":2}'::jsonb, true),
('u7-mcq-9', 'mcq', array['quiz']::text[], 1, '{"answerIndex":1}'::jsonb, true),
('u7-mcq-10', 'mcq', array['quiz']::text[], 1, '{"answerIndex":1}'::jsonb, true),
('u7-mcq-11', 'mcq', array['quiz']::text[], 1, '{"answerIndex":2}'::jsonb, true),
('u7-mcq-12', 'mcq', array['quiz']::text[], 1, '{"answerIndex":0}'::jsonb, true),
('u7-ct-1', 'code-predict', array['code']::text[], 2, '{"answer":"15","accept":["15"]}'::jsonb, true),
('u7-ct-2', 'code-predict', array['code']::text[], 2, '{"answer":"3\n2\n1","accept":["3\n2\n1","3 2 1","321"]}'::jsonb, true),
('u7-ct-3', 'code-predict', array['code']::text[], 1, '{"answer":"Pass","accept":["Pass"]}'::jsonb, true),
('u7-ct-4', 'code-parsons', array['code']::text[], 2, '{"lines":["INPUT Number","IF Number >= 0","   THEN","      OUTPUT \"Positive\"","   ELSE","      OUTPUT \"Negative\"","ENDIF"],"distractors":["WHILE Number >= 0 DO","NEXT Number"]}'::jsonb, true),
('u7-ct-5', 'code-parsons', array['code']::text[], 2, '{"lines":["Total ← 0","FOR i ← 1 TO 10","   Total ← Total + i","NEXT i","OUTPUT Total"],"distractors":["WHILE i <= 10 DO","Total ← Total - i"]}'::jsonb, true),
('u7-ct-6', 'code-fill', array['code']::text[], 2, '{"blanks":[{"id":"1","accept":["<>"],"caseSensitive":false},{"id":"2","accept":["ENDWHILE"],"caseSensitive":true}]}'::jsonb, true),
('u7-ct-7', 'code-fill', array['code']::text[], 2, '{"blanks":[{"id":"1","accept":["OTHERWISE"],"caseSensitive":true},{"id":"2","accept":["ENDCASE"],"caseSensitive":true}]}'::jsonb, true),
('u8-fc-1', 'flashcard', array['match', 'memory']::text[], 1, '{"term":"Variable","definition":"A named storage location whose value can change while the program runs."}'::jsonb, true),
('u8-fc-2', 'flashcard', array['match', 'memory']::text[], 1, '{"term":"Constant","definition":"A named value that is fixed and does not change while the program runs."}'::jsonb, true),
('u8-fc-3', 'flashcard', array['match', 'memory']::text[], 1, '{"term":"Integer","definition":"A whole-number data type, e.g. 7 or -3."}'::jsonb, true),
('u8-fc-4', 'flashcard', array['match', 'memory']::text[], 1, '{"term":"Real","definition":"A number data type that includes a decimal/fractional part, e.g. 3.14."}'::jsonb, true),
('u8-fc-5', 'flashcard', array['match', 'memory']::text[], 1, '{"term":"Char","definition":"A data type holding a single character, e.g. ''A''."}'::jsonb, true),
('u8-fc-6', 'flashcard', array['match', 'memory']::text[], 1, '{"term":"String","definition":"A data type holding a sequence of characters, e.g. \"Hello\"."}'::jsonb, true),
('u8-fc-7', 'flashcard', array['match', 'memory']::text[], 1, '{"term":"Boolean","definition":"A data type with only two possible values: True or False."}'::jsonb, true),
('u8-fc-8', 'flashcard', array['match', 'memory']::text[], 2, '{"term":"Casting","definition":"Converting data from one type to another, e.g. int(\"5\") converts the string \"5\" to the integer 5."}'::jsonb, true),
('u8-fc-9', 'flashcard', array['match', 'memory']::text[], 1, '{"term":"Sequence","definition":"Program statements carried out in order, from top to bottom."}'::jsonb, true),
('u8-fc-10', 'flashcard', array['match', 'memory']::text[], 1, '{"term":"Selection","definition":"Choosing which code to run based on a condition, using IF or CASE statements."}'::jsonb, true),
('u8-fc-11', 'flashcard', array['match', 'memory']::text[], 1, '{"term":"Iteration","definition":"Repeating code using a loop: count-controlled (FOR) or condition-controlled (WHILE)."}'::jsonb, true),
('u8-fc-12', 'flashcard', array['match', 'memory']::text[], 1, '{"term":"Count-controlled loop","definition":"A loop that repeats a set number of times, e.g. a FOR loop."}'::jsonb, true),
('u8-fc-13', 'flashcard', array['match', 'memory']::text[], 2, '{"term":"Pre-condition loop","definition":"A loop that checks its condition before the body runs, e.g. a WHILE loop."}'::jsonb, true),
('u8-fc-14', 'flashcard', array['match', 'memory']::text[], 1, '{"term":"Totalling","definition":"Keeping a running total by adding each value to it, e.g. total = total + value."}'::jsonb, true),
('u8-fc-15', 'flashcard', array['match', 'memory']::text[], 1, '{"term":"Counting","definition":"Increasing a counter, e.g. count = count + 1."}'::jsonb, true),
('u8-fc-16', 'flashcard', array['match', 'memory']::text[], 2, '{"term":"MOD","definition":"Gives the remainder after a division; in Python this is the % operator, e.g. 17 MOD 5 = 2."}'::jsonb, true),
('u8-fc-17', 'flashcard', array['match', 'memory']::text[], 2, '{"term":"DIV","definition":"Gives the whole-number (integer) part of a division; in Python this is the // operator, e.g. 17 DIV 5 = 3."}'::jsonb, true),
('u8-fc-18', 'flashcard', array['match', 'memory']::text[], 1, '{"term":"Relational operators","definition":"Operators that compare values: = , < , <= , > , >= , <> (in Python: ==, <, <=, >, >=, !=)."}'::jsonb, true),
('u8-fc-19', 'flashcard', array['match', 'memory']::text[], 1, '{"term":"Logical operators","definition":"Operators that combine conditions: AND, OR, NOT."}'::jsonb, true),
('u8-fc-20', 'flashcard', array['match', 'memory']::text[], 1, '{"term":"String length","definition":"The number of characters in a string; found with LENGTH (Python len()), e.g. len(\"Hello\") = 5."}'::jsonb, true),
('u8-fc-21', 'flashcard', array['match', 'memory']::text[], 1, '{"term":"Substring","definition":"A part of a string taken from a start position for a given length."}'::jsonb, true),
('u8-mcq-1', 'mcq', array['quiz']::text[], 1, '{"answerIndex":2}'::jsonb, true),
('u8-mcq-2', 'mcq', array['quiz']::text[], 2, '{"answerIndex":1}'::jsonb, true),
('u8-mcq-3', 'mcq', array['quiz']::text[], 1, '{"answerIndex":1}'::jsonb, true),
('u8-mcq-4', 'mcq', array['quiz']::text[], 2, '{"answerIndex":1}'::jsonb, true),
('u8-mcq-5', 'mcq', array['quiz']::text[], 2, '{"answerIndex":1}'::jsonb, true),
('u8-mcq-6', 'mcq', array['quiz']::text[], 1, '{"answerIndex":1}'::jsonb, true),
('u8-mcq-7', 'mcq', array['quiz']::text[], 1, '{"answerIndex":2}'::jsonb, true),
('u8-mcq-8', 'mcq', array['quiz']::text[], 1, '{"answerIndex":2}'::jsonb, true),
('u8-mcq-9', 'mcq', array['quiz']::text[], 1, '{"answerIndex":1}'::jsonb, true),
('u8-mcq-10', 'mcq', array['quiz']::text[], 2, '{"answerIndex":2}'::jsonb, true),
('u8-mcq-11', 'mcq', array['quiz']::text[], 1, '{"answerIndex":1}'::jsonb, true),
('u8-mcq-12', 'mcq', array['quiz']::text[], 1, '{"answerIndex":1}'::jsonb, true),
('u8-ct-1', 'code-predict', array['code']::text[], 2, '{"answer":"15","accept":["15"]}'::jsonb, true),
('u8-ct-2', 'code-predict', array['code']::text[], 2, '{"answer":"5\n4\n3","accept":["5\n4\n3","5 4 3","543"]}'::jsonb, true),
('u8-ct-3', 'code-predict', array['code']::text[], 2, '{"answer":"2\n3","accept":["2\n3","2 3","23"]}'::jsonb, true),
('u8-ct-4', 'code-predict', array['code']::text[], 1, '{"answer":"DATA\n4","accept":["DATA\n4","DATA 4"]}'::jsonb, true),
('u8-ct-5', 'code-fill', array['code']::text[], 2, '{"blanks":[{"id":"1","accept":["11"],"caseSensitive":false},{"id":"2","accept":["print"],"caseSensitive":true}]}'::jsonb, true),
('u8-ct-6', 'code-fill', array['code']::text[], 1, '{"blanks":[{"id":"1","accept":["int"],"caseSensitive":true}]}'::jsonb, true),
('u8-ct-7', 'code-parsons', array['code']::text[], 2, '{"lines":["mark = int(input(\"Enter mark: \"))","if mark >= 50:","    print(\"Pass\")","else:","    print(\"Fail\")"],"distractors":["while mark >= 50:","    print(Pass)"]}'::jsonb, true),
('u8-ct-8', 'code-parsons', array['code']::text[], 3, '{"lines":["total = 0","number = int(input(\"Enter a number: \"))","while number != 0:","    total = total + number","    number = int(input(\"Enter a number: \"))","print(total)"],"distractors":["for number in range(0):","total = total - number"]}'::jsonb, true),
('convert-denary-binary:value', 'conversion', array['convert']::text[], 2, null, true),
('convert-binary-denary:value', 'conversion', array['convert']::text[], 2, null, true),
('convert-denary-hex:value', 'conversion', array['convert']::text[], 2, null, true),
('convert-hex-denary:value', 'conversion', array['convert']::text[], 2, null, true),
('convert-binary-add:8bit', 'conversion', array['convert']::text[], 2, null, true),
('convert-shift:1bit', 'conversion', array['convert']::text[], 2, null, true),
('convert-twos-complement:8bit', 'conversion', array['convert']::text[], 2, null, true),
('convert-file-size:image', 'conversion', array['convert']::text[], 2, null, true),
('convert-file-size:sound', 'conversion', array['convert']::text[], 2, null, true)
on conflict (item_id) do update set
  content_kind = excluded.content_kind,
  ranked_activities = excluded.ranked_activities,
  difficulty = excluded.difficulty,
  answer_key = excluded.answer_key,
  ranked_enabled = excluded.ranked_enabled;
